version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
  frontend:
    image: node:14
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: ["npm", "start"]
